# Generated by Django 3.2.16 on 2022-12-17 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20221217_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='status_cat',
            field=models.IntegerField(choices=[(0, 'Off'), (1, 'ON'), (2, 'Disabled')], default=2),
        ),
        migrations.AddField(
            model_name='category',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
