# Generated by Django 3.2.16 on 2022-12-17 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20221217_1101'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['-updated_on']},
        ),
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='category',
            name='status_cat',
            field=models.IntegerField(choices=[(0, 'OFF'), (1, 'ON'), (2, 'Disabled')], default=2),
        ),
    ]
